# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Programs/CPP/NeuralNetwork

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Programs/CPP/NeuralNetwork

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Programs/CPP/NeuralNetwork/CMakeFiles /home/pi/Programs/CPP/NeuralNetwork/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Programs/CPP/NeuralNetwork/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Net

# Build rule for target.
Net: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Net
.PHONY : Net

# fast build rule for target.
Net/fast:
	$(MAKE) -f CMakeFiles/Net.dir/build.make CMakeFiles/Net.dir/build
.PHONY : Net/fast

#=============================================================================
# Target rules for targets named NeuralNetwork

# Build rule for target.
NeuralNetwork: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NeuralNetwork
.PHONY : NeuralNetwork

# fast build rule for target.
NeuralNetwork/fast:
	$(MAKE) -f lib/NeuralNetwork/CMakeFiles/NeuralNetwork.dir/build.make lib/NeuralNetwork/CMakeFiles/NeuralNetwork.dir/build
.PHONY : NeuralNetwork/fast

tests/Hello_NeuralNet/main.o: tests/Hello_NeuralNet/main.cpp.o

.PHONY : tests/Hello_NeuralNet/main.o

# target to build an object file
tests/Hello_NeuralNet/main.cpp.o:
	$(MAKE) -f CMakeFiles/Net.dir/build.make CMakeFiles/Net.dir/tests/Hello_NeuralNet/main.cpp.o
.PHONY : tests/Hello_NeuralNet/main.cpp.o

tests/Hello_NeuralNet/main.i: tests/Hello_NeuralNet/main.cpp.i

.PHONY : tests/Hello_NeuralNet/main.i

# target to preprocess a source file
tests/Hello_NeuralNet/main.cpp.i:
	$(MAKE) -f CMakeFiles/Net.dir/build.make CMakeFiles/Net.dir/tests/Hello_NeuralNet/main.cpp.i
.PHONY : tests/Hello_NeuralNet/main.cpp.i

tests/Hello_NeuralNet/main.s: tests/Hello_NeuralNet/main.cpp.s

.PHONY : tests/Hello_NeuralNet/main.s

# target to generate assembly for a file
tests/Hello_NeuralNet/main.cpp.s:
	$(MAKE) -f CMakeFiles/Net.dir/build.make CMakeFiles/Net.dir/tests/Hello_NeuralNet/main.cpp.s
.PHONY : tests/Hello_NeuralNet/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Net"
	@echo "... NeuralNetwork"
	@echo "... tests/Hello_NeuralNet/main.o"
	@echo "... tests/Hello_NeuralNet/main.i"
	@echo "... tests/Hello_NeuralNet/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

